// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-fetch';
import type { CheckLicenceData, CheckLicenceResponse, GetLicenceStatusData, GetLicenceStatusResponse } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class LicencingService {
    public static checkLicence<ThrowOnError extends boolean = false>(options?: Options<CheckLicenceData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<CheckLicenceResponse, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbhost-licencing/v2.0/check-licence/check-licence',
            ...options
        });
    }
    
    public static getLicenceStatus<ThrowOnError extends boolean = false>(options?: Options<GetLicenceStatusData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetLicenceStatusResponse, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbhost-licencing/v2.0/get-licence-status/get-licence-status',
            ...options
        });
    }
    
}