// This file is auto-generated by @hey-api/openapi-ts

export type CheckLicenseResponse = {
    readonly accepted: string;
    readonly timeLeft: string;
};

export type LicenceAddon = {
    name: string;
    nextDueDate: string;
    status: string;
};

export type LicenceStatusResponseReadable = {
    readonly expiryDateTime: string;
    regDate: string;
    status: string;
    readonly validDomains: string;
    readonly validPaths: string;
    licenceAddons: Array<LicenceAddon>;
    readonly isDevelopmentLicense: boolean;
};

export type LicenceStatusResponseWritable = {
    regDate: string;
    status: string;
    licenceAddons: Array<LicenceAddon>;
};

export type CheckLicenceData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/umbhost-licencing/v2.0/check-licence/check-licence';
};

export type CheckLicenceErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type CheckLicenceResponses = {
    /**
     * Accepted
     */
    202: CheckLicenseResponse;
};

export type CheckLicenceResponse = CheckLicenceResponses[keyof CheckLicenceResponses];

export type GetLicenceStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/umbhost-licencing/v2.0/get-licence-status/get-licence-status';
};

export type GetLicenceStatusErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetLicenceStatusResponses = {
    /**
     * Accepted
     */
    202: LicenceStatusResponseReadable;
};

export type GetLicenceStatusResponse = GetLicenceStatusResponses[keyof GetLicenceStatusResponses];

export type ClientOptions = {
    baseUrl: 'https://localhost:44390' | (string & {});
};