import type { UmbLocalizationDictionary } from '@umbraco-cms/backoffice/localization-api';

export default {
    umbcheckout: {
        company_name: "UmbHost Limited",
        workspace_title: "UmbCheckout",
        sidebar_menu: "UmbCheckout",
        sidebar_overview: "Overview",
        documentation_url: "https://docs.umbcheckout.net/",
        product_url: "https://umbcheckout.net",
        workspace_overview_title: "Help & Support",
        workspace_overview_introduction_documentation_available_at: 'Documentation available at',
        workspace_overview_configuration: "Configuration",
        unlicenced_warning_mode: 'UmbCheckout is running in unlicenced mode, please',
        unlicenced_warning_purchase: "purchase a licence",
        unlicenced_warning_support: "support development",
        github_report_issues: "Please report any issues in the bug tracker found on the",
        github_report_issues_url: "https://github.com/UmbHost/UmbCheckout/issues",
        github_report_repo: "UmbCheckout GitHub repository",
        support_ticket_or: " or ",
        support_ticket: "create a support ticket",
        support_ticket_url: "https://my.umbhost.net/submitticket.php?step=2&deptid=8&subject=UmbCheckout:%20[ISSUE%20NAME%20HERE]",
        licence_details: "License Details",
        licence_status: "License Status",
        licence_registration_date: "License Registration Date",
        licence_expiry_date: "License Expiry Date",
        licence_valid_domains: "Valid Domains",
        licence_valid_paths: "Valid Path",
        licence_recheck: "Recheck License",
        license_development: "Development License",
        license_development_true: "Yes",
        license_check_requested_title: "License Check Requested",
        license_check_requested_message: "Your license has been checked, please wait for the response.",
        umbraco_application_url_unset: 'The "Umbraco Application Url" configuration setting is unset, you can read how to <a href="https://docs.umbraco.com/umbraco-cms/reference/configuration/webroutingsettings#umbraco-application-url" target="_blank">set the value here</a>.<br /> This is required to match your license.',
        license_check_request_wait_title: "Please wait to re-check the license",
        license_check_request_wait_message: (remaining: string) =>  `You can try again in ${remaining}`,
        license_addon: "License Addon",
        license_addon_name: "Addon Name",
        made_with: "Made with",
        made_by: "by",
        success_page_url_label: "Success Page URL",
        success_page_url_description: "The URL to redirect to after a successful payment.",
        cancel_page_url_label: "Cancel Page URL",
        cancel_page_url_description: "The URL to redirect to after a cancelled payment.",
        currency_code_label: "Currency Code",
        currency_code_description: "The currency code to use for payments, e.g. 'USD' for US Dollars.",
        enable_shipping_label: "Enable Shipping",
        enable_shipping_description: "Enable shipping options for the checkout process.",
        store_basket_cookie_label: "Store Basket in Cookie",
        store_basket_cookie_description: "Store the basket in a cookie to persist it across sessions.",
        store_basket_cookie_expiry_label: "Basket Cookie Expiry",
        store_basket_cookie_expiry_description: "The duration in days for which the basket cookie will be valid.",
        store_basket_database_label: "Store Basket in Database",
        store_basket_database_description: "Store the basket in the database to persist it across sessions.",
        store_basket_database_expiry_label: "Basket Database Expiry",
        store_basket_database_expiry_description: "The duration in days for which the basket database will be valid.",
        configuration_saved_title: "Configuration Saved",
        configuration_saved_message: "Your configuration has been saved successfully.",
        configuration_failed_save_title: "Configuration Save Failed",
        configuration_failed_save_message: "There was an error saving your configuration. Please try again later."
    }
} as UmbLocalizationDictionary;