// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-fetch';
import type { GetUmbracoUmbcheckoutV10ConfigurationApiGetConfigurationData, GetUmbracoUmbcheckoutV10ConfigurationApiHasUmbracoApplicationUrlSetData, PatchUmbracoUmbcheckoutV10ConfigurationApiUpdateConfigurationData, GetUmbracoUmbcheckoutV10StripeCustomerApiGetCustomerData, GetUmbracoUmbcheckoutV10StripeInvoicesApiGetInvoiceData, GetUmbracoUmbcheckoutV10StripeInvoicesApiGetInvoicesData, GetUmbracoUmbcheckoutV10StripePaymentsApiGetChargeData, GetUmbracoUmbcheckoutV10StripePaymentsApiGetPaymentsData, GetUmbracoUmbcheckoutV10StripePaymentsApiGetRefundData, GetUmbracoUmbcheckoutV10StripeRefundsApiGetRefundsData, PutUmbracoUmbcheckoutV10StripeRefundsApiRefundPaymentData, GetUmbracoUmbcheckoutV10StripeSettingsGetSettingsData, PatchUmbracoUmbcheckoutV10StripeSettingsUpdateSettingsData, PutUmbracoUmbcheckoutV10StripeShippingRatesCreateShippingRateData, DeleteUmbracoUmbcheckoutV10StripeShippingRatesDeleteShippingRateData, GetUmbracoUmbcheckoutV10StripeShippingRatesGetShippingRateData, GetUmbracoUmbcheckoutV10StripeShippingRatesGetShippingRatesData, GetUmbracoUmbcheckoutV10StripeShippingRatesGetStripeShippingRateData, GetUmbracoUmbcheckoutV10StripeShippingRatesGetStripeShippingRatesData, PatchUmbracoUmbcheckoutV10StripeShippingRatesUpdateShippingRateData, PutUmbracoUmbcheckoutV10StripeTaxRatesApiCreateTaxRateData, DeleteUmbracoUmbcheckoutV10StripeTaxRatesApiDeleteTaxRateData, GetUmbracoUmbcheckoutV10StripeTaxRatesApiGetStripeTaxRateData, GetUmbracoUmbcheckoutV10StripeTaxRatesApiGetStripeTaxRatesData, GetUmbracoUmbcheckoutV10StripeTaxRatesApiGetTaxRateData, GetUmbracoUmbcheckoutV10StripeTaxRatesApiGetTaxRatesData, PatchUmbracoUmbcheckoutV10StripeTaxRatesApiUpdateTaxRateData, PostUmbracoUmbcheckoutV10StripeWebhookApiCheckoutEventsData } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class ConfigurationService {
    public static getUmbracoUmbcheckoutV10ConfigurationApiGetConfiguration<ThrowOnError extends boolean = false>(options?: Options<GetUmbracoUmbcheckoutV10ConfigurationApiGetConfigurationData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbcheckout/v1.0/configuration-api/get-configuration',
            ...options
        });
    }
    
    public static getUmbracoUmbcheckoutV10ConfigurationApiHasUmbracoApplicationUrlSet<ThrowOnError extends boolean = false>(options?: Options<GetUmbracoUmbcheckoutV10ConfigurationApiHasUmbracoApplicationUrlSetData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbcheckout/v1.0/configuration-api/has-umbraco-application-url-set',
            ...options
        });
    }
    
    public static patchUmbracoUmbcheckoutV10ConfigurationApiUpdateConfiguration<ThrowOnError extends boolean = false>(options?: Options<PatchUmbracoUmbcheckoutV10ConfigurationApiUpdateConfigurationData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).patch<unknown, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbcheckout/v1.0/configuration-api/update-configuration',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
}

export class StripeCustomerService {
    public static getUmbracoUmbcheckoutV10StripeCustomerApiGetCustomer<ThrowOnError extends boolean = false>(options?: Options<GetUmbracoUmbcheckoutV10StripeCustomerApiGetCustomerData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbcheckout/v1.0/stripe/customer-api/get-customer',
            ...options
        });
    }
    
}

export class StripeInvoicesService {
    public static getUmbracoUmbcheckoutV10StripeInvoicesApiGetInvoice<ThrowOnError extends boolean = false>(options?: Options<GetUmbracoUmbcheckoutV10StripeInvoicesApiGetInvoiceData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbcheckout/v1.0/stripe/invoices-api/get-invoice',
            ...options
        });
    }
    
    public static getUmbracoUmbcheckoutV10StripeInvoicesApiGetInvoices<ThrowOnError extends boolean = false>(options?: Options<GetUmbracoUmbcheckoutV10StripeInvoicesApiGetInvoicesData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbcheckout/v1.0/stripe/invoices-api/get-invoices',
            ...options
        });
    }
    
}

export class StripePaymentsService {
    public static getUmbracoUmbcheckoutV10StripePaymentsApiGetCharge<ThrowOnError extends boolean = false>(options?: Options<GetUmbracoUmbcheckoutV10StripePaymentsApiGetChargeData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbcheckout/v1.0/stripe/payments-api/get-charge',
            ...options
        });
    }
    
    public static getUmbracoUmbcheckoutV10StripePaymentsApiGetPayments<ThrowOnError extends boolean = false>(options?: Options<GetUmbracoUmbcheckoutV10StripePaymentsApiGetPaymentsData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbcheckout/v1.0/stripe/payments-api/get-payments',
            ...options
        });
    }
    
    public static getUmbracoUmbcheckoutV10StripePaymentsApiGetRefund<ThrowOnError extends boolean = false>(options?: Options<GetUmbracoUmbcheckoutV10StripePaymentsApiGetRefundData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbcheckout/v1.0/stripe/payments-api/get-refund',
            ...options
        });
    }
    
}

export class StripeRefundsService {
    public static getUmbracoUmbcheckoutV10StripeRefundsApiGetRefunds<ThrowOnError extends boolean = false>(options?: Options<GetUmbracoUmbcheckoutV10StripeRefundsApiGetRefundsData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbcheckout/v1.0/stripe/refunds-api/get-refunds',
            ...options
        });
    }
    
    public static putUmbracoUmbcheckoutV10StripeRefundsApiRefundPayment<ThrowOnError extends boolean = false>(options?: Options<PutUmbracoUmbcheckoutV10StripeRefundsApiRefundPaymentData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).put<unknown, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbcheckout/v1.0/stripe/refunds-api/refund-payment',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
}

export class StripeSettingsService {
    public static getUmbracoUmbcheckoutV10StripeSettingsGetSettings<ThrowOnError extends boolean = false>(options?: Options<GetUmbracoUmbcheckoutV10StripeSettingsGetSettingsData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbcheckout/v1.0/stripe/settings/get-settings',
            ...options
        });
    }
    
    public static patchUmbracoUmbcheckoutV10StripeSettingsUpdateSettings<ThrowOnError extends boolean = false>(options?: Options<PatchUmbracoUmbcheckoutV10StripeSettingsUpdateSettingsData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).patch<unknown, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbcheckout/v1.0/stripe/settings/update-settings',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
}

export class StripeShippingRatesService {
    public static putUmbracoUmbcheckoutV10StripeShippingRatesCreateShippingRate<ThrowOnError extends boolean = false>(options?: Options<PutUmbracoUmbcheckoutV10StripeShippingRatesCreateShippingRateData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).put<unknown, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbcheckout/v1.0/stripe/shipping-rates/create-shipping-rate',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    public static deleteUmbracoUmbcheckoutV10StripeShippingRatesDeleteShippingRate<ThrowOnError extends boolean = false>(options?: Options<DeleteUmbracoUmbcheckoutV10StripeShippingRatesDeleteShippingRateData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).delete<unknown, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbcheckout/v1.0/stripe/shipping-rates/delete-shipping-rate',
            ...options
        });
    }
    
    public static getUmbracoUmbcheckoutV10StripeShippingRatesGetShippingRate<ThrowOnError extends boolean = false>(options?: Options<GetUmbracoUmbcheckoutV10StripeShippingRatesGetShippingRateData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbcheckout/v1.0/stripe/shipping-rates/get-shipping-rate',
            ...options
        });
    }
    
    public static getUmbracoUmbcheckoutV10StripeShippingRatesGetShippingRates<ThrowOnError extends boolean = false>(options?: Options<GetUmbracoUmbcheckoutV10StripeShippingRatesGetShippingRatesData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbcheckout/v1.0/stripe/shipping-rates/get-shipping-rates',
            ...options
        });
    }
    
    public static getUmbracoUmbcheckoutV10StripeShippingRatesGetStripeShippingRate<ThrowOnError extends boolean = false>(options?: Options<GetUmbracoUmbcheckoutV10StripeShippingRatesGetStripeShippingRateData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbcheckout/v1.0/stripe/shipping-rates/get-stripe-shipping-rate',
            ...options
        });
    }
    
    public static getUmbracoUmbcheckoutV10StripeShippingRatesGetStripeShippingRates<ThrowOnError extends boolean = false>(options?: Options<GetUmbracoUmbcheckoutV10StripeShippingRatesGetStripeShippingRatesData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbcheckout/v1.0/stripe/shipping-rates/get-stripe-shipping-rates',
            ...options
        });
    }
    
    public static patchUmbracoUmbcheckoutV10StripeShippingRatesUpdateShippingRate<ThrowOnError extends boolean = false>(options?: Options<PatchUmbracoUmbcheckoutV10StripeShippingRatesUpdateShippingRateData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).patch<unknown, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbcheckout/v1.0/stripe/shipping-rates/update-shipping-rate',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
}

export class StripeTaxRatesService {
    public static putUmbracoUmbcheckoutV10StripeTaxRatesApiCreateTaxRate<ThrowOnError extends boolean = false>(options?: Options<PutUmbracoUmbcheckoutV10StripeTaxRatesApiCreateTaxRateData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).put<unknown, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbcheckout/v1.0/stripe/tax-rates-api/create-tax-rate',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    public static deleteUmbracoUmbcheckoutV10StripeTaxRatesApiDeleteTaxRate<ThrowOnError extends boolean = false>(options?: Options<DeleteUmbracoUmbcheckoutV10StripeTaxRatesApiDeleteTaxRateData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).delete<unknown, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbcheckout/v1.0/stripe/tax-rates-api/delete-tax-rate',
            ...options
        });
    }
    
    public static getUmbracoUmbcheckoutV10StripeTaxRatesApiGetStripeTaxRate<ThrowOnError extends boolean = false>(options?: Options<GetUmbracoUmbcheckoutV10StripeTaxRatesApiGetStripeTaxRateData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbcheckout/v1.0/stripe/tax-rates-api/get-stripe-tax-rate',
            ...options
        });
    }
    
    public static getUmbracoUmbcheckoutV10StripeTaxRatesApiGetStripeTaxRates<ThrowOnError extends boolean = false>(options?: Options<GetUmbracoUmbcheckoutV10StripeTaxRatesApiGetStripeTaxRatesData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbcheckout/v1.0/stripe/tax-rates-api/get-stripe-tax-rates',
            ...options
        });
    }
    
    public static getUmbracoUmbcheckoutV10StripeTaxRatesApiGetTaxRate<ThrowOnError extends boolean = false>(options?: Options<GetUmbracoUmbcheckoutV10StripeTaxRatesApiGetTaxRateData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbcheckout/v1.0/stripe/tax-rates-api/get-tax-rate',
            ...options
        });
    }
    
    public static getUmbracoUmbcheckoutV10StripeTaxRatesApiGetTaxRates<ThrowOnError extends boolean = false>(options?: Options<GetUmbracoUmbcheckoutV10StripeTaxRatesApiGetTaxRatesData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbcheckout/v1.0/stripe/tax-rates-api/get-tax-rates',
            ...options
        });
    }
    
    public static patchUmbracoUmbcheckoutV10StripeTaxRatesApiUpdateTaxRate<ThrowOnError extends boolean = false>(options?: Options<PatchUmbracoUmbcheckoutV10StripeTaxRatesApiUpdateTaxRateData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).patch<unknown, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbcheckout/v1.0/stripe/tax-rates-api/update-tax-rate',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
}

export class StripeWebhooksService {
    public static postUmbracoUmbcheckoutV10StripeWebhookApiCheckoutEvents<ThrowOnError extends boolean = false>(options?: Options<PostUmbracoUmbcheckoutV10StripeWebhookApiCheckoutEventsData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).post<unknown, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbcheckout/v1.0/stripe/webhook-api/checkout-events',
            ...options
        });
    }
    
}