// This file is auto-generated by @hey-api/openapi-ts

export type ConfigurationValue = {
    successPageUrl: Array<MultiUrlPicker>;
    currencyCode: string;
    cancelPageUrl: Array<MultiUrlPicker>;
    storeBasketInCookie: string;
    basketInCookieExpiry: number;
    storeBasketInDatabase: string;
    basketInDatabaseExpiry: number;
    enableShipping: string;
};

export enum EventMessageTypeModel {
    DEFAULT = 'Default',
    INFO = 'Info',
    ERROR = 'Error',
    SUCCESS = 'Success',
    WARNING = 'Warning'
}

export type MultiUrlPicker = {
    name: string;
    udi: string;
    url: string;
    icon: string;
    published: boolean;
    trashed: boolean;
};

export type NotificationHeaderModel = {
    message: string;
    category: string;
    type: EventMessageTypeModel;
};

export type RefundPayment = {
    id: string;
};

export type ShippingRate = {
    id: number;
    key: string;
    name: string;
    value: string;
};

export type StripeSettingsValue = {
    useLiveApiDetails: string;
    collectPhoneNumber: string;
    collectPromotionalEmailsConsent: string;
    shippingAllowedCountries?: string | null;
    allowPromotionalCodes: string;
    enableAbandonedCartRecovery: string;
    allowPromotionalCodesOnRecoveredCarts: string;
};

export type TaxRate = {
    id: number;
    key: string;
    name: string;
    value: string;
};

export type GetUmbracoUmbcheckoutV10ConfigurationApiGetConfigurationData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/umbcheckout/v1.0/configuration-api/get-configuration';
};

export type GetUmbracoUmbcheckoutV10ConfigurationApiGetConfigurationErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type GetUmbracoUmbcheckoutV10ConfigurationApiGetConfigurationResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type GetUmbracoUmbcheckoutV10ConfigurationApiHasUmbracoApplicationUrlSetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/umbcheckout/v1.0/configuration-api/has-umbraco-application-url-set';
};

export type GetUmbracoUmbcheckoutV10ConfigurationApiHasUmbracoApplicationUrlSetErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type GetUmbracoUmbcheckoutV10ConfigurationApiHasUmbracoApplicationUrlSetResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type PatchUmbracoUmbcheckoutV10ConfigurationApiUpdateConfigurationData = {
    body?: ConfigurationValue;
    path?: never;
    query?: never;
    url: '/umbraco/umbcheckout/v1.0/configuration-api/update-configuration';
};

export type PatchUmbracoUmbcheckoutV10ConfigurationApiUpdateConfigurationErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type PatchUmbracoUmbcheckoutV10ConfigurationApiUpdateConfigurationResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type GetUmbracoUmbcheckoutV10StripeCustomerApiGetCustomerData = {
    body?: never;
    path?: never;
    query?: {
        id?: string;
    };
    url: '/umbraco/umbcheckout/v1.0/stripe/customer-api/get-customer';
};

export type GetUmbracoUmbcheckoutV10StripeCustomerApiGetCustomerErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type GetUmbracoUmbcheckoutV10StripeCustomerApiGetCustomerResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type GetUmbracoUmbcheckoutV10StripeInvoicesApiGetInvoiceData = {
    body?: never;
    path?: never;
    query?: {
        id?: string;
    };
    url: '/umbraco/umbcheckout/v1.0/stripe/invoices-api/get-invoice';
};

export type GetUmbracoUmbcheckoutV10StripeInvoicesApiGetInvoiceErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type GetUmbracoUmbcheckoutV10StripeInvoicesApiGetInvoiceResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type GetUmbracoUmbcheckoutV10StripeInvoicesApiGetInvoicesData = {
    body?: never;
    path?: never;
    query?: {
        status?: string;
        created?: string;
        page?: string;
        limit?: number;
    };
    url: '/umbraco/umbcheckout/v1.0/stripe/invoices-api/get-invoices';
};

export type GetUmbracoUmbcheckoutV10StripeInvoicesApiGetInvoicesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type GetUmbracoUmbcheckoutV10StripeInvoicesApiGetInvoicesResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type GetUmbracoUmbcheckoutV10StripePaymentsApiGetChargeData = {
    body?: never;
    path?: never;
    query?: {
        id?: string;
    };
    url: '/umbraco/umbcheckout/v1.0/stripe/payments-api/get-charge';
};

export type GetUmbracoUmbcheckoutV10StripePaymentsApiGetChargeErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type GetUmbracoUmbcheckoutV10StripePaymentsApiGetChargeResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type GetUmbracoUmbcheckoutV10StripePaymentsApiGetPaymentsData = {
    body?: never;
    path?: never;
    query?: {
        status?: string;
        created?: string;
        page?: string;
        limit?: number;
    };
    url: '/umbraco/umbcheckout/v1.0/stripe/payments-api/get-payments';
};

export type GetUmbracoUmbcheckoutV10StripePaymentsApiGetPaymentsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type GetUmbracoUmbcheckoutV10StripePaymentsApiGetPaymentsResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type GetUmbracoUmbcheckoutV10StripePaymentsApiGetRefundData = {
    body?: never;
    path?: never;
    query?: {
        id?: string;
    };
    url: '/umbraco/umbcheckout/v1.0/stripe/payments-api/get-refund';
};

export type GetUmbracoUmbcheckoutV10StripePaymentsApiGetRefundErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type GetUmbracoUmbcheckoutV10StripePaymentsApiGetRefundResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type GetUmbracoUmbcheckoutV10StripeRefundsApiGetRefundsData = {
    body?: never;
    path?: never;
    query?: {
        created?: string;
        startingAfter?: string;
        limit?: number;
    };
    url: '/umbraco/umbcheckout/v1.0/stripe/refunds-api/get-refunds';
};

export type GetUmbracoUmbcheckoutV10StripeRefundsApiGetRefundsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type GetUmbracoUmbcheckoutV10StripeRefundsApiGetRefundsResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type PutUmbracoUmbcheckoutV10StripeRefundsApiRefundPaymentData = {
    body?: RefundPayment;
    path?: never;
    query?: never;
    url: '/umbraco/umbcheckout/v1.0/stripe/refunds-api/refund-payment';
};

export type PutUmbracoUmbcheckoutV10StripeRefundsApiRefundPaymentErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type PutUmbracoUmbcheckoutV10StripeRefundsApiRefundPaymentResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type GetUmbracoUmbcheckoutV10StripeSettingsGetSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/umbcheckout/v1.0/stripe/settings/get-settings';
};

export type GetUmbracoUmbcheckoutV10StripeSettingsGetSettingsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type GetUmbracoUmbcheckoutV10StripeSettingsGetSettingsResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type PatchUmbracoUmbcheckoutV10StripeSettingsUpdateSettingsData = {
    body?: StripeSettingsValue;
    path?: never;
    query?: never;
    url: '/umbraco/umbcheckout/v1.0/stripe/settings/update-settings';
};

export type PatchUmbracoUmbcheckoutV10StripeSettingsUpdateSettingsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type PatchUmbracoUmbcheckoutV10StripeSettingsUpdateSettingsResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type PutUmbracoUmbcheckoutV10StripeShippingRatesCreateShippingRateData = {
    body?: ShippingRate;
    path?: never;
    query?: never;
    url: '/umbraco/umbcheckout/v1.0/stripe/shipping-rates/create-shipping-rate';
};

export type PutUmbracoUmbcheckoutV10StripeShippingRatesCreateShippingRateErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type PutUmbracoUmbcheckoutV10StripeShippingRatesCreateShippingRateResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type DeleteUmbracoUmbcheckoutV10StripeShippingRatesDeleteShippingRateData = {
    body?: never;
    path?: never;
    query?: {
        key?: string;
    };
    url: '/umbraco/umbcheckout/v1.0/stripe/shipping-rates/delete-shipping-rate';
};

export type DeleteUmbracoUmbcheckoutV10StripeShippingRatesDeleteShippingRateErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type DeleteUmbracoUmbcheckoutV10StripeShippingRatesDeleteShippingRateResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type GetUmbracoUmbcheckoutV10StripeShippingRatesGetShippingRateData = {
    body?: never;
    path?: never;
    query?: {
        key?: string;
    };
    url: '/umbraco/umbcheckout/v1.0/stripe/shipping-rates/get-shipping-rate';
};

export type GetUmbracoUmbcheckoutV10StripeShippingRatesGetShippingRateErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetUmbracoUmbcheckoutV10StripeShippingRatesGetShippingRateResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type GetUmbracoUmbcheckoutV10StripeShippingRatesGetShippingRatesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/umbcheckout/v1.0/stripe/shipping-rates/get-shipping-rates';
};

export type GetUmbracoUmbcheckoutV10StripeShippingRatesGetShippingRatesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetUmbracoUmbcheckoutV10StripeShippingRatesGetShippingRatesResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type GetUmbracoUmbcheckoutV10StripeShippingRatesGetStripeShippingRateData = {
    body?: never;
    path?: never;
    query?: {
        id?: string;
    };
    url: '/umbraco/umbcheckout/v1.0/stripe/shipping-rates/get-stripe-shipping-rate';
};

export type GetUmbracoUmbcheckoutV10StripeShippingRatesGetStripeShippingRateErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetUmbracoUmbcheckoutV10StripeShippingRatesGetStripeShippingRateResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type GetUmbracoUmbcheckoutV10StripeShippingRatesGetStripeShippingRatesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/umbcheckout/v1.0/stripe/shipping-rates/get-stripe-shipping-rates';
};

export type GetUmbracoUmbcheckoutV10StripeShippingRatesGetStripeShippingRatesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetUmbracoUmbcheckoutV10StripeShippingRatesGetStripeShippingRatesResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type PatchUmbracoUmbcheckoutV10StripeShippingRatesUpdateShippingRateData = {
    body?: ShippingRate;
    path?: never;
    query?: never;
    url: '/umbraco/umbcheckout/v1.0/stripe/shipping-rates/update-shipping-rate';
};

export type PatchUmbracoUmbcheckoutV10StripeShippingRatesUpdateShippingRateErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type PatchUmbracoUmbcheckoutV10StripeShippingRatesUpdateShippingRateResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type PutUmbracoUmbcheckoutV10StripeTaxRatesApiCreateTaxRateData = {
    body?: TaxRate;
    path?: never;
    query?: never;
    url: '/umbraco/umbcheckout/v1.0/stripe/tax-rates-api/create-tax-rate';
};

export type PutUmbracoUmbcheckoutV10StripeTaxRatesApiCreateTaxRateErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type PutUmbracoUmbcheckoutV10StripeTaxRatesApiCreateTaxRateResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type DeleteUmbracoUmbcheckoutV10StripeTaxRatesApiDeleteTaxRateData = {
    body?: never;
    path?: never;
    query?: {
        key?: string;
    };
    url: '/umbraco/umbcheckout/v1.0/stripe/tax-rates-api/delete-tax-rate';
};

export type DeleteUmbracoUmbcheckoutV10StripeTaxRatesApiDeleteTaxRateErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type DeleteUmbracoUmbcheckoutV10StripeTaxRatesApiDeleteTaxRateResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type GetUmbracoUmbcheckoutV10StripeTaxRatesApiGetStripeTaxRateData = {
    body?: never;
    path?: never;
    query?: {
        id?: string;
    };
    url: '/umbraco/umbcheckout/v1.0/stripe/tax-rates-api/get-stripe-tax-rate';
};

export type GetUmbracoUmbcheckoutV10StripeTaxRatesApiGetStripeTaxRateErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type GetUmbracoUmbcheckoutV10StripeTaxRatesApiGetStripeTaxRateResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type GetUmbracoUmbcheckoutV10StripeTaxRatesApiGetStripeTaxRatesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/umbcheckout/v1.0/stripe/tax-rates-api/get-stripe-tax-rates';
};

export type GetUmbracoUmbcheckoutV10StripeTaxRatesApiGetStripeTaxRatesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type GetUmbracoUmbcheckoutV10StripeTaxRatesApiGetStripeTaxRatesResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type GetUmbracoUmbcheckoutV10StripeTaxRatesApiGetTaxRateData = {
    body?: never;
    path?: never;
    query?: {
        key?: string;
    };
    url: '/umbraco/umbcheckout/v1.0/stripe/tax-rates-api/get-tax-rate';
};

export type GetUmbracoUmbcheckoutV10StripeTaxRatesApiGetTaxRateErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type GetUmbracoUmbcheckoutV10StripeTaxRatesApiGetTaxRateResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type GetUmbracoUmbcheckoutV10StripeTaxRatesApiGetTaxRatesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/umbcheckout/v1.0/stripe/tax-rates-api/get-tax-rates';
};

export type GetUmbracoUmbcheckoutV10StripeTaxRatesApiGetTaxRatesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type GetUmbracoUmbcheckoutV10StripeTaxRatesApiGetTaxRatesResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type PatchUmbracoUmbcheckoutV10StripeTaxRatesApiUpdateTaxRateData = {
    body?: TaxRate;
    path?: never;
    query?: never;
    url: '/umbraco/umbcheckout/v1.0/stripe/tax-rates-api/update-tax-rate';
};

export type PatchUmbracoUmbcheckoutV10StripeTaxRatesApiUpdateTaxRateErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type PatchUmbracoUmbcheckoutV10StripeTaxRatesApiUpdateTaxRateResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type PostUmbracoUmbcheckoutV10StripeWebhookApiCheckoutEventsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/umbcheckout/v1.0/stripe/webhook-api/checkout-events';
};

export type PostUmbracoUmbcheckoutV10StripeWebhookApiCheckoutEventsErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type PostUmbracoUmbcheckoutV10StripeWebhookApiCheckoutEventsResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type ClientOptions = {
    baseUrl: 'https://localhost:44390' | (string & {});
};