// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-fetch';
import type { GetConfigurationData, GetConfigurationResponse, HasUmbracoApplicationUrlSetData, HasUmbracoApplicationUrlSetResponse, UpdateConfigurationData, UpdateConfigurationResponse, GetCustomerData, GetInvoiceData, GetInvoicesData, GetChargeData, GetPaymentsData, GetRefundData, GetRefundsData, RefundPaymentData, GetStripeSettingsData, UpdateStripeSettingsData, CreateShippingRateData, DeleteShippingRateData, GetShippingRateData, GetShippingRatesData, GetStripeShippingRateData, GetStripeShippingRatesData, UpdateShippingRateData, CreateTaxRateData, DeleteTaxRateData, GetStripeTaxRateData, GetStripeTaxRatesData, GetTaxRateData, GetTaxRatesData, UpdateTaxRateData, CheckoutEventsData } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class ConfigurationService {
    public static getConfiguration<ThrowOnError extends boolean = false>(options?: Options<GetConfigurationData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetConfigurationResponse, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbcheckout/v2.0/configuration-api/get-configuration',
            ...options
        });
    }
    
    public static hasUmbracoApplicationUrlSet<ThrowOnError extends boolean = false>(options?: Options<HasUmbracoApplicationUrlSetData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<HasUmbracoApplicationUrlSetResponse, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbcheckout/v2.0/configuration-api/has-umbraco-application-url-set',
            ...options
        });
    }
    
    public static updateConfiguration<ThrowOnError extends boolean = false>(options?: Options<UpdateConfigurationData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).patch<UpdateConfigurationResponse, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbcheckout/v2.0/configuration-api/update-configuration',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
}

export class StripeCustomerService {
    public static getCustomer<ThrowOnError extends boolean = false>(options?: Options<GetCustomerData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbcheckout/v2.0/stripe/customer-api/get-customer',
            ...options
        });
    }
    
}

export class StripeInvoicesService {
    public static getInvoice<ThrowOnError extends boolean = false>(options?: Options<GetInvoiceData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbcheckout/v2.0/stripe/invoices-api/get-invoice',
            ...options
        });
    }
    
    public static getInvoices<ThrowOnError extends boolean = false>(options?: Options<GetInvoicesData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbcheckout/v2.0/stripe/invoices-api/get-invoices',
            ...options
        });
    }
    
}

export class StripePaymentsService {
    public static getCharge<ThrowOnError extends boolean = false>(options?: Options<GetChargeData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbcheckout/v2.0/stripe/payments-api/get-charge',
            ...options
        });
    }
    
    public static getPayments<ThrowOnError extends boolean = false>(options?: Options<GetPaymentsData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbcheckout/v2.0/stripe/payments-api/get-payments',
            ...options
        });
    }
    
    public static getRefund<ThrowOnError extends boolean = false>(options?: Options<GetRefundData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbcheckout/v2.0/stripe/payments-api/get-refund',
            ...options
        });
    }
    
}

export class StripeRefundsService {
    public static getRefunds<ThrowOnError extends boolean = false>(options?: Options<GetRefundsData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbcheckout/v2.0/stripe/refunds-api/get-refunds',
            ...options
        });
    }
    
    public static refundPayment<ThrowOnError extends boolean = false>(options?: Options<RefundPaymentData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).put<unknown, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbcheckout/v2.0/stripe/refunds-api/refund-payment',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
}

export class StripeSettingsService {
    public static getStripeSettings<ThrowOnError extends boolean = false>(options?: Options<GetStripeSettingsData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbcheckout/v2.0/stripe/settings/get-settings',
            ...options
        });
    }
    
    public static updateStripeSettings<ThrowOnError extends boolean = false>(options?: Options<UpdateStripeSettingsData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).patch<unknown, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbcheckout/v2.0/stripe/settings/update-settings',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
}

export class StripeShippingRatesService {
    public static createShippingRate<ThrowOnError extends boolean = false>(options?: Options<CreateShippingRateData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).put<unknown, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbcheckout/v2.0/stripe/shipping-rates/create-shipping-rate',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    public static deleteShippingRate<ThrowOnError extends boolean = false>(options?: Options<DeleteShippingRateData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).delete<unknown, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbcheckout/v2.0/stripe/shipping-rates/delete-shipping-rate',
            ...options
        });
    }
    
    public static getShippingRate<ThrowOnError extends boolean = false>(options?: Options<GetShippingRateData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbcheckout/v2.0/stripe/shipping-rates/get-shipping-rate',
            ...options
        });
    }
    
    public static getShippingRates<ThrowOnError extends boolean = false>(options?: Options<GetShippingRatesData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbcheckout/v2.0/stripe/shipping-rates/get-shipping-rates',
            ...options
        });
    }
    
    public static getStripeShippingRate<ThrowOnError extends boolean = false>(options?: Options<GetStripeShippingRateData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbcheckout/v2.0/stripe/shipping-rates/get-stripe-shipping-rate',
            ...options
        });
    }
    
    public static getStripeShippingRates<ThrowOnError extends boolean = false>(options?: Options<GetStripeShippingRatesData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbcheckout/v2.0/stripe/shipping-rates/get-stripe-shipping-rates',
            ...options
        });
    }
    
    public static updateShippingRate<ThrowOnError extends boolean = false>(options?: Options<UpdateShippingRateData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).patch<unknown, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbcheckout/v2.0/stripe/shipping-rates/update-shipping-rate',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
}

export class StripeTaxRatesService {
    public static createTaxRate<ThrowOnError extends boolean = false>(options?: Options<CreateTaxRateData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).put<unknown, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbcheckout/v2.0/stripe/tax-rates-api/create-tax-rate',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    public static deleteTaxRate<ThrowOnError extends boolean = false>(options?: Options<DeleteTaxRateData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).delete<unknown, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbcheckout/v2.0/stripe/tax-rates-api/delete-tax-rate',
            ...options
        });
    }
    
    public static getStripeTaxRate<ThrowOnError extends boolean = false>(options?: Options<GetStripeTaxRateData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbcheckout/v2.0/stripe/tax-rates-api/get-stripe-tax-rate',
            ...options
        });
    }
    
    public static getStripeTaxRates<ThrowOnError extends boolean = false>(options?: Options<GetStripeTaxRatesData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbcheckout/v2.0/stripe/tax-rates-api/get-stripe-tax-rates',
            ...options
        });
    }
    
    public static getTaxRate<ThrowOnError extends boolean = false>(options?: Options<GetTaxRateData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbcheckout/v2.0/stripe/tax-rates-api/get-tax-rate',
            ...options
        });
    }
    
    public static getTaxRates<ThrowOnError extends boolean = false>(options?: Options<GetTaxRatesData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbcheckout/v2.0/stripe/tax-rates-api/get-tax-rates',
            ...options
        });
    }
    
    public static updateTaxRate<ThrowOnError extends boolean = false>(options?: Options<UpdateTaxRateData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).patch<unknown, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbcheckout/v2.0/stripe/tax-rates-api/update-tax-rate',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
}

export class StripeWebhooksService {
    public static checkoutEvents<ThrowOnError extends boolean = false>(options?: Options<CheckoutEventsData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).post<unknown, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/umbcheckout/v2.0/stripe/webhook-api/checkout-events',
            ...options
        });
    }
    
}