// This file is auto-generated by @hey-api/openapi-ts

export type Config = {
    minNumber: number;
    maxNumber: number;
    overlaySize?: string | null;
    hideAnchor: boolean;
    ignoreUserStartNodes: boolean;
    maxChars: number;
};

export type ConfigurationValue = {
    successPageUrl: Array<MultiUrlPicker>;
    currencyCode: string;
    cancelPageUrl: Array<MultiUrlPicker>;
    storeBasketInCookie: boolean;
    basketInCookieExpiry: number;
    storeBasketInDatabase: boolean;
    basketInDatabaseExpiry: number;
    enableShipping: boolean;
};

export enum EventMessageTypeModel {
    DEFAULT = 'Default',
    INFO = 'Info',
    ERROR = 'Error',
    SUCCESS = 'Success',
    WARNING = 'Warning'
}

export type MultiUrlPicker = {
    name: string;
    udi: string;
    url: string;
    icon: string;
    published: boolean;
    trashed: boolean;
};

export type NotificationHeaderModel = {
    message: string;
    category: string;
    type: EventMessageTypeModel;
};

export type Property = {
    alias: string;
    description: string;
    label: string;
    value: unknown;
    validation: Validation;
    config?: Config | null;
    editorUiAlias: string;
};

export type RefundPayment = {
    id: string;
};

export type ShippingRate = {
    id: number;
    key: string;
    name: string;
    value: string;
};

export type StripeSettingsValue = {
    useLiveApiDetails: string;
    collectPhoneNumber: string;
    collectPromotionalEmailsConsent: string;
    shippingAllowedCountries?: string | null;
    allowPromotionalCodes: string;
    enableAbandonedCartRecovery: string;
    allowPromotionalCodesOnRecoveredCarts: string;
};

export type TaxRate = {
    id: number;
    key: string;
    name: string;
    value: string;
};

export type Validation = {
    mandatory: boolean;
    mandatoryMessage: string;
    regEx: string;
    regExMessage: string;
};

export type GetConfigurationData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/umbcheckout/v2.0/configuration-api/get-configuration';
};

export type GetConfigurationErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetConfigurationResponses = {
    /**
     * Accepted
     */
    202: Array<Property>;
};

export type GetConfigurationResponse = GetConfigurationResponses[keyof GetConfigurationResponses];

export type HasUmbracoApplicationUrlSetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/umbcheckout/v2.0/configuration-api/has-umbraco-application-url-set';
};

export type HasUmbracoApplicationUrlSetErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type HasUmbracoApplicationUrlSetResponses = {
    /**
     * Accepted
     */
    202: boolean;
};

export type HasUmbracoApplicationUrlSetResponse = HasUmbracoApplicationUrlSetResponses[keyof HasUmbracoApplicationUrlSetResponses];

export type UpdateConfigurationData = {
    body?: ConfigurationValue;
    path?: never;
    query?: never;
    url: '/umbraco/umbcheckout/v2.0/configuration-api/update-configuration';
};

export type UpdateConfigurationErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type UpdateConfigurationResponses = {
    /**
     * Accepted
     */
    202: Array<Property>;
};

export type UpdateConfigurationResponse = UpdateConfigurationResponses[keyof UpdateConfigurationResponses];

export type GetCustomerData = {
    body?: never;
    path?: never;
    query?: {
        id?: string;
    };
    url: '/umbraco/umbcheckout/v2.0/stripe/customer-api/get-customer';
};

export type GetCustomerErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type GetCustomerResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type GetInvoiceData = {
    body?: never;
    path?: never;
    query?: {
        id?: string;
    };
    url: '/umbraco/umbcheckout/v2.0/stripe/invoices-api/get-invoice';
};

export type GetInvoiceErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type GetInvoiceResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type GetInvoicesData = {
    body?: never;
    path?: never;
    query?: {
        status?: string;
        created?: string;
        page?: string;
        limit?: number;
    };
    url: '/umbraco/umbcheckout/v2.0/stripe/invoices-api/get-invoices';
};

export type GetInvoicesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type GetInvoicesResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type GetChargeData = {
    body?: never;
    path?: never;
    query?: {
        id?: string;
    };
    url: '/umbraco/umbcheckout/v2.0/stripe/payments-api/get-charge';
};

export type GetChargeErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type GetChargeResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type GetPaymentsData = {
    body?: never;
    path?: never;
    query?: {
        status?: string;
        created?: string;
        page?: string;
        limit?: number;
    };
    url: '/umbraco/umbcheckout/v2.0/stripe/payments-api/get-payments';
};

export type GetPaymentsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type GetPaymentsResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type GetRefundData = {
    body?: never;
    path?: never;
    query?: {
        id?: string;
    };
    url: '/umbraco/umbcheckout/v2.0/stripe/payments-api/get-refund';
};

export type GetRefundErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type GetRefundResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type GetRefundsData = {
    body?: never;
    path?: never;
    query?: {
        created?: string;
        startingAfter?: string;
        limit?: number;
    };
    url: '/umbraco/umbcheckout/v2.0/stripe/refunds-api/get-refunds';
};

export type GetRefundsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type GetRefundsResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type RefundPaymentData = {
    body?: RefundPayment;
    path?: never;
    query?: never;
    url: '/umbraco/umbcheckout/v2.0/stripe/refunds-api/refund-payment';
};

export type RefundPaymentErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type RefundPaymentResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type GetStripeSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/umbcheckout/v2.0/stripe/settings/get-settings';
};

export type GetStripeSettingsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetStripeSettingsResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type UpdateStripeSettingsData = {
    body?: StripeSettingsValue;
    path?: never;
    query?: never;
    url: '/umbraco/umbcheckout/v2.0/stripe/settings/update-settings';
};

export type UpdateStripeSettingsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type UpdateStripeSettingsResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type CreateShippingRateData = {
    body?: ShippingRate;
    path?: never;
    query?: never;
    url: '/umbraco/umbcheckout/v2.0/stripe/shipping-rates/create-shipping-rate';
};

export type CreateShippingRateErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type CreateShippingRateResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type DeleteShippingRateData = {
    body?: never;
    path?: never;
    query?: {
        key?: string;
    };
    url: '/umbraco/umbcheckout/v2.0/stripe/shipping-rates/delete-shipping-rate';
};

export type DeleteShippingRateErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type DeleteShippingRateResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type GetShippingRateData = {
    body?: never;
    path?: never;
    query?: {
        key?: string;
    };
    url: '/umbraco/umbcheckout/v2.0/stripe/shipping-rates/get-shipping-rate';
};

export type GetShippingRateErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetShippingRateResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type GetShippingRatesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/umbcheckout/v2.0/stripe/shipping-rates/get-shipping-rates';
};

export type GetShippingRatesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetShippingRatesResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type GetStripeShippingRateData = {
    body?: never;
    path?: never;
    query?: {
        id?: string;
    };
    url: '/umbraco/umbcheckout/v2.0/stripe/shipping-rates/get-stripe-shipping-rate';
};

export type GetStripeShippingRateErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetStripeShippingRateResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type GetStripeShippingRatesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/umbcheckout/v2.0/stripe/shipping-rates/get-stripe-shipping-rates';
};

export type GetStripeShippingRatesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetStripeShippingRatesResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type UpdateShippingRateData = {
    body?: ShippingRate;
    path?: never;
    query?: never;
    url: '/umbraco/umbcheckout/v2.0/stripe/shipping-rates/update-shipping-rate';
};

export type UpdateShippingRateErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type UpdateShippingRateResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type CreateTaxRateData = {
    body?: TaxRate;
    path?: never;
    query?: never;
    url: '/umbraco/umbcheckout/v2.0/stripe/tax-rates-api/create-tax-rate';
};

export type CreateTaxRateErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type CreateTaxRateResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type DeleteTaxRateData = {
    body?: never;
    path?: never;
    query?: {
        key?: string;
    };
    url: '/umbraco/umbcheckout/v2.0/stripe/tax-rates-api/delete-tax-rate';
};

export type DeleteTaxRateErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type DeleteTaxRateResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type GetStripeTaxRateData = {
    body?: never;
    path?: never;
    query?: {
        id?: string;
    };
    url: '/umbraco/umbcheckout/v2.0/stripe/tax-rates-api/get-stripe-tax-rate';
};

export type GetStripeTaxRateErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type GetStripeTaxRateResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type GetStripeTaxRatesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/umbcheckout/v2.0/stripe/tax-rates-api/get-stripe-tax-rates';
};

export type GetStripeTaxRatesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type GetStripeTaxRatesResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type GetTaxRateData = {
    body?: never;
    path?: never;
    query?: {
        key?: string;
    };
    url: '/umbraco/umbcheckout/v2.0/stripe/tax-rates-api/get-tax-rate';
};

export type GetTaxRateErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type GetTaxRateResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type GetTaxRatesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/umbcheckout/v2.0/stripe/tax-rates-api/get-tax-rates';
};

export type GetTaxRatesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type GetTaxRatesResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type UpdateTaxRateData = {
    body?: TaxRate;
    path?: never;
    query?: never;
    url: '/umbraco/umbcheckout/v2.0/stripe/tax-rates-api/update-tax-rate';
};

export type UpdateTaxRateErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type UpdateTaxRateResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type CheckoutEventsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/umbcheckout/v2.0/stripe/webhook-api/checkout-events';
};

export type CheckoutEventsErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type CheckoutEventsResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type ClientOptions = {
    baseUrl: 'https://localhost:44390' | (string & {});
};